### ISSUE TITLE
Any plans to complete the Alt example referenced in the readme?

### ISSUE THREAD

**Issue by genyded** [AdamBrodzinski/meteor-flux-leaderboard#14]
Hey Adam,

I know you are super busy but was wondering if you have any plans to complete the Alt example referenced towards the bottom of your readme? We've been using Meteor for quite awhile but are new to React and recently VERY new to Flux and it's varying flavors. We're being pushed to use Alt because of it's container abstraction and overall effort to decrease boilerplate. But I cannot find a good example of Meteor and Alt (ideally with React in the mix) anywhere and all your stuff is usually very solid so I keep checking for this and frowning.

If you have no time or plans for this that's cool - just let me know! I'll close this and keep looking.

**Comment by genyded** [comment]
Disregard, I found it... but you may want to update the link in the readme.

**Comment by AdamBrodzinski** [comment]
Will accept a PR. I've stopped using Alt and am migrating over to Redux because it's more simple and less boilerplate.
